version: '3.8'

services:
  loginapi:
    image: loginapi:latest 
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3022:3022"
    environment:
     - PORT=3022
     - APLICATION_URL=https://loginapi.adjunto.com.br
     - APLICATION_PRINCIPAL_URL=https://chatwoot.adjunto.com.br
     - DB_DIALECT=postgres
     - DB_HOST=postgres
     - DB_PORT=5432
     - DB_DATABASE=userDB
     - DB_USERNAME=postgres
     - DB_PASSWORD=Adjunto7411135
     - JWT_SECRET=your_jwt_secret
     - ENCRYPTION_KEY=4a7b1f8c5d9e3b6f1c2d4e5f7a8b9c1d2e3f4a5b6c7d8e9f0a1b2c3d4e5f6a7b
     - JWT_EXPIRES_IN=1d
     - ROOT_USER=admin@adjunto.com.br
     - ROOT_PASSWORD=A@djunto7411135
     - NODE_ENV=production  
     - MAILER_SENDER_EMAIL="Adjunto <suporte@adjunto.com.br>"
     - SMTP_DOMAIN=hostinger.com
     - SMTP_ADDRESS=smtp.hostinger.com
     - SMTP_PORT=465
     - SMTP_USERNAME=admin@adjunto.com.br
     - SMTP_PASSWORD=A@djunto7411135
     - SMTP_AUTHENTICATION=plain
     - SMTP_ENABLE_STARTTLS_AUTO=true
     - SMTP_OPENSSL_VERIFY_MODE=none
     - SMTP_TLS=true
     - SMTP_SSL=true
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
      restart_policy:
        condition: on-failure     
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.loginapi.rule=Host(`loginapi.adjunto.com.br`)" # Substitua pelo seu domínio
      - "traefik.http.routers.loginapi.entrypoints=websecure"
      - "traefik.http.routers.loginapi.tls.certresolver=le" # Certificado SSL LetsEncrypt
      - "traefik.http.services.loginapi.loadbalancer.server.port=3022"
    networks:
      - traefik_public
      - digital_network

networks:
  traefik_public:
    external: true
  digital_network:
    external: true
